# Schema for the theme setting configuration file of the wxttheme theme.

#wxttheme.settings:
#  type: theme_settings
#  label: 'wxttheme settings'
#  mapping:
#    cdn_provider:
#      type: string
#      label: 'CDN Provider'
#    breadcrumb_home:
#      type: integer
#      label: 'Breadcrumb Home'
